version: '3.8'

services:
  structurizr:
    image: structurizr/lite
    container_name: structurizr-lite
    volumes:
      - ./workspace:/usr/local/structurizr
    ports:
      - "8080:8080"
    restart: unless-stopped
