services:
  structurizr:
    image: structurizr/lite
    container_name: structurizr-lite
    volumes:
      - ${PROJECT_PATH:-./projects/example-project}:/usr/local/structurizr
    ports:
      - "8080:8080"
    restart: unless-stopped
